#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SwimmingTool.Resource", IsApplication=true)]

namespace SwimmingTool
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.Data.Resource.String.library_name = global::SwimmingTool.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowDraggingColumn = global::SwimmingTool.Resource.Attribute.allowDraggingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowDraggingRow = global::SwimmingTool.Resource.Attribute.allowDraggingRow;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowEditing = global::SwimmingTool.Resource.Attribute.allowEditing;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowGroupExpandCollapse = global::SwimmingTool.Resource.Attribute.allowGroupExpandCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowLoadMore = global::SwimmingTool.Resource.Attribute.allowLoadMore;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowMultiSorting = global::SwimmingTool.Resource.Attribute.allowMultiSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowNull = global::SwimmingTool.Resource.Attribute.allowNull;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowPullToRefresh = global::SwimmingTool.Resource.Attribute.allowPullToRefresh;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowResizingColumn = global::SwimmingTool.Resource.Attribute.allowResizingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowSorting = global::SwimmingTool.Resource.Attribute.allowSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowSwiping = global::SwimmingTool.Resource.Attribute.allowSwiping;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.allowTriStateSorting = global::SwimmingTool.Resource.Attribute.allowTriStateSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.alternationCount = global::SwimmingTool.Resource.Attribute.alternationCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.autoExpandGroups = global::SwimmingTool.Resource.Attribute.autoExpandGroups;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.autoGenerateColumns = global::SwimmingTool.Resource.Attribute.autoGenerateColumns;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.borderColor = global::SwimmingTool.Resource.Attribute.borderColor;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.columnSizer = global::SwimmingTool.Resource.Attribute.columnSizer;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.culture = global::SwimmingTool.Resource.Attribute.culture;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.editTapAction = global::SwimmingTool.Resource.Attribute.editTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.editorSelectionBehavior = global::SwimmingTool.Resource.Attribute.editorSelectionBehavior;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.enableGroupSeparator = global::SwimmingTool.Resource.Attribute.enableGroupSeparator;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.fontSize = global::SwimmingTool.Resource.Attribute.fontSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.frozenColumnsCount = global::SwimmingTool.Resource.Attribute.frozenColumnsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.frozenRowsCount = global::SwimmingTool.Resource.Attribute.frozenRowsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.gridRowHeight = global::SwimmingTool.Resource.Attribute.gridRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.gridSelectionMode = global::SwimmingTool.Resource.Attribute.gridSelectionMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.groupingMode = global::SwimmingTool.Resource.Attribute.groupingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.headerRowHeight = global::SwimmingTool.Resource.Attribute.headerRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.indentColumnWidth = global::SwimmingTool.Resource.Attribute.indentColumnWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.isBusy = global::SwimmingTool.Resource.Attribute.isBusy;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.loadMorePosition = global::SwimmingTool.Resource.Attribute.loadMorePosition;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.loadMoreText = global::SwimmingTool.Resource.Attribute.loadMoreText;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.maxSwipeOffset = global::SwimmingTool.Resource.Attribute.maxSwipeOffset;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.maximumDecimalDigits = global::SwimmingTool.Resource.Attribute.maximumDecimalDigits;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numberFormat = global::SwimmingTool.Resource.Attribute.numberFormat;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numericButtonBackground = global::SwimmingTool.Resource.Attribute.numericButtonBackground;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numericButtonCount = global::SwimmingTool.Resource.Attribute.numericButtonCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.numericTextBoxValue = global::SwimmingTool.Resource.Attribute.numericTextBoxValue;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.orientation = global::SwimmingTool.Resource.Attribute.orientation;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.pageCount = global::SwimmingTool.Resource.Attribute.pageCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.pageSize = global::SwimmingTool.Resource.Attribute.pageSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.parsingMode = global::SwimmingTool.Resource.Attribute.parsingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.percentDisplayMode = global::SwimmingTool.Resource.Attribute.percentDisplayMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.resizingMode = global::SwimmingTool.Resource.Attribute.resizingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.rowHeaderWidth = global::SwimmingTool.Resource.Attribute.rowHeaderWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.scrollingMode = global::SwimmingTool.Resource.Attribute.scrollingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.selectAllOnFocus = global::SwimmingTool.Resource.Attribute.selectAllOnFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.selectedIndex = global::SwimmingTool.Resource.Attribute.selectedIndex;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.selectionForeground = global::SwimmingTool.Resource.Attribute.selectionForeground;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.showRowHeader = global::SwimmingTool.Resource.Attribute.showRowHeader;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.sortTapAction = global::SwimmingTool.Resource.Attribute.sortTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.useOnDemandPaging = global::SwimmingTool.Resource.Attribute.useOnDemandPaging;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.valueChangeMode = global::SwimmingTool.Resource.Attribute.valueChangeMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.verticalOverScrollMode = global::SwimmingTool.Resource.Attribute.verticalOverScrollMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.watermark = global::SwimmingTool.Resource.Attribute.watermark;
			global::Syncfusion.SfDataGrid.Android.Resource.Attribute.watermarkColor = global::SwimmingTool.Resource.Attribute.watermarkColor;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Ascending = global::SwimmingTool.Resource.Drawable.Ascending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Descending = global::SwimmingTool.Resource.Drawable.Descending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Drag_and_Drop_Icon = global::SwimmingTool.Resource.Drawable.Drag_and_Drop_Icon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragDown = global::SwimmingTool.Resource.Drawable.DragDown;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragUp = global::SwimmingTool.Resource.Drawable.DragUp;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.error2 = global::SwimmingTool.Resource.Drawable.error2;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.FirstPageIcon = global::SwimmingTool.Resource.Drawable.FirstPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupCollapse = global::SwimmingTool.Resource.Drawable.GroupCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupExpander = global::SwimmingTool.Resource.Drawable.GroupExpander;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupIcon_Android = global::SwimmingTool.Resource.Drawable.GroupIcon_Android;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.LastPageIcon = global::SwimmingTool.Resource.Drawable.LastPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.NextPageIcon = global::SwimmingTool.Resource.Drawable.NextPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.PrevPageIcon = global::SwimmingTool.Resource.Drawable.PrevPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.ResizingIcon = global::SwimmingTool.Resource.Drawable.ResizingIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Sort = global::SwimmingTool.Resource.Drawable.Sort;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.SortDescending = global::SwimmingTool.Resource.Drawable.SortDescending;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.auto = global::SwimmingTool.Resource.Id.auto;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.bottom = global::SwimmingTool.Resource.Id.bottom;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.bounce = global::SwimmingTool.Resource.Id.bounce;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.compute = global::SwimmingTool.Resource.Id.compute;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.decimalMode = global::SwimmingTool.Resource.Id.decimalMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.doubleMode = global::SwimmingTool.Resource.Id.doubleMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.doubleTap = global::SwimmingTool.Resource.Id.doubleTap;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.horizontal = global::SwimmingTool.Resource.Id.horizontal;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.lastCoulmnFill = global::SwimmingTool.Resource.Id.lastCoulmnFill;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.line = global::SwimmingTool.Resource.Id.line;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.moveLast = global::SwimmingTool.Resource.Id.moveLast;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.multiple = global::SwimmingTool.Resource.Id.multiple;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.none = global::SwimmingTool.Resource.Id.none;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onKeyFocus = global::SwimmingTool.Resource.Id.onKeyFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onLostFocus = global::SwimmingTool.Resource.Id.onLostFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onMoved = global::SwimmingTool.Resource.Id.onMoved;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onTap = global::SwimmingTool.Resource.Id.onTap;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.onTouchUp = global::SwimmingTool.Resource.Id.onTouchUp;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.pixel = global::SwimmingTool.Resource.Id.pixel;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.pixelLine = global::SwimmingTool.Resource.Id.pixelLine;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.selectAll = global::SwimmingTool.Resource.Id.selectAll;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.single = global::SwimmingTool.Resource.Id.single;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.singleDeSelect = global::SwimmingTool.Resource.Id.singleDeSelect;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.singleTap = global::SwimmingTool.Resource.Id.singleTap;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.star = global::SwimmingTool.Resource.Id.star;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.top = global::SwimmingTool.Resource.Id.top;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.value = global::SwimmingTool.Resource.Id.value;
			global::Syncfusion.SfDataGrid.Android.Resource.Id.vertical = global::SwimmingTool.Resource.Id.vertical;
			global::Syncfusion.SfDataGrid.Android.Resource.Layout.ScrollViewer = global::SwimmingTool.Resource.Layout.ScrollViewer;
			global::Syncfusion.SfDataGrid.Android.Resource.String.library_name = global::SwimmingTool.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid = global::SwimmingTool.Resource.Styleable.SfDataGrid;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowDraggingColumn = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowDraggingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowDraggingRow = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowDraggingRow;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowEditing = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowEditing;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowGroupExpandCollapse = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowGroupExpandCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowLoadMore = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowLoadMore;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowMultiSorting = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowMultiSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowPullToRefresh = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowPullToRefresh;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowResizingColumn = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowResizingColumn;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowSorting = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowSwiping = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowSwiping;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_allowTriStateSorting = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowTriStateSorting;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_alternationCount = global::SwimmingTool.Resource.Styleable.SfDataGrid_alternationCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_autoExpandGroups = global::SwimmingTool.Resource.Styleable.SfDataGrid_autoExpandGroups;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_autoGenerateColumns = global::SwimmingTool.Resource.Styleable.SfDataGrid_autoGenerateColumns;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_columnSizer = global::SwimmingTool.Resource.Styleable.SfDataGrid_columnSizer;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_editTapAction = global::SwimmingTool.Resource.Styleable.SfDataGrid_editTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_editorSelectionBehavior = global::SwimmingTool.Resource.Styleable.SfDataGrid_editorSelectionBehavior;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_frozenColumnsCount = global::SwimmingTool.Resource.Styleable.SfDataGrid_frozenColumnsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_frozenRowsCount = global::SwimmingTool.Resource.Styleable.SfDataGrid_frozenRowsCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_gridRowHeight = global::SwimmingTool.Resource.Styleable.SfDataGrid_gridRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_gridSelectionMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_gridSelectionMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_groupingMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_groupingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_headerRowHeight = global::SwimmingTool.Resource.Styleable.SfDataGrid_headerRowHeight;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_indentColumnWidth = global::SwimmingTool.Resource.Styleable.SfDataGrid_indentColumnWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_isBusy = global::SwimmingTool.Resource.Styleable.SfDataGrid_isBusy;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_loadMorePosition = global::SwimmingTool.Resource.Styleable.SfDataGrid_loadMorePosition;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_loadMoreText = global::SwimmingTool.Resource.Styleable.SfDataGrid_loadMoreText;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_maxSwipeOffset = global::SwimmingTool.Resource.Styleable.SfDataGrid_maxSwipeOffset;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_resizingMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_resizingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_rowHeaderWidth = global::SwimmingTool.Resource.Styleable.SfDataGrid_rowHeaderWidth;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_scrollingMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_scrollingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_selectedIndex = global::SwimmingTool.Resource.Styleable.SfDataGrid_selectedIndex;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_showRowHeader = global::SwimmingTool.Resource.Styleable.SfDataGrid_showRowHeader;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_sortTapAction = global::SwimmingTool.Resource.Styleable.SfDataGrid_sortTapAction;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataGrid_verticalOverScrollMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_verticalOverScrollMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager = global::SwimmingTool.Resource.Styleable.SfDataPager;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_numericButtonBackground = global::SwimmingTool.Resource.Styleable.SfDataPager_numericButtonBackground;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_numericButtonCount = global::SwimmingTool.Resource.Styleable.SfDataPager_numericButtonCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_orientation = global::SwimmingTool.Resource.Styleable.SfDataPager_orientation;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_pageCount = global::SwimmingTool.Resource.Styleable.SfDataPager_pageCount;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_pageSize = global::SwimmingTool.Resource.Styleable.SfDataPager_pageSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_selectionForeground = global::SwimmingTool.Resource.Styleable.SfDataPager_selectionForeground;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfDataPager_useOnDemandPaging = global::SwimmingTool.Resource.Styleable.SfDataPager_useOnDemandPaging;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox = global::SwimmingTool.Resource.Styleable.SfNumericTextBox;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_allowNull = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_allowNull;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_borderColor = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_borderColor;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_culture = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_culture;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_enableGroupSeparator = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_enableGroupSeparator;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_fontSize = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_fontSize;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_numberFormat = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_numberFormat;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_numericTextBoxValue = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_numericTextBoxValue;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_parsingMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_parsingMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_percentDisplayMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_percentDisplayMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_selectAllOnFocus = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_selectAllOnFocus;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_valueChangeMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_valueChangeMode;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_watermark = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_watermark;
			global::Syncfusion.SfDataGrid.Android.Resource.Styleable.SfNumericTextBox_watermarkColor = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_watermarkColor;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowDraggingColumn = global::SwimmingTool.Resource.Attribute.allowDraggingColumn;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowDraggingRow = global::SwimmingTool.Resource.Attribute.allowDraggingRow;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowEditing = global::SwimmingTool.Resource.Attribute.allowEditing;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowGroupExpandCollapse = global::SwimmingTool.Resource.Attribute.allowGroupExpandCollapse;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowLoadMore = global::SwimmingTool.Resource.Attribute.allowLoadMore;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowMultiSorting = global::SwimmingTool.Resource.Attribute.allowMultiSorting;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowNull = global::SwimmingTool.Resource.Attribute.allowNull;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowPullToRefresh = global::SwimmingTool.Resource.Attribute.allowPullToRefresh;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowResizingColumn = global::SwimmingTool.Resource.Attribute.allowResizingColumn;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowSorting = global::SwimmingTool.Resource.Attribute.allowSorting;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowSwiping = global::SwimmingTool.Resource.Attribute.allowSwiping;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.allowTriStateSorting = global::SwimmingTool.Resource.Attribute.allowTriStateSorting;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.alternationCount = global::SwimmingTool.Resource.Attribute.alternationCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.autoExpandGroups = global::SwimmingTool.Resource.Attribute.autoExpandGroups;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.autoGenerateColumns = global::SwimmingTool.Resource.Attribute.autoGenerateColumns;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.borderColor = global::SwimmingTool.Resource.Attribute.borderColor;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.columnSizer = global::SwimmingTool.Resource.Attribute.columnSizer;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.culture = global::SwimmingTool.Resource.Attribute.culture;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.editTapAction = global::SwimmingTool.Resource.Attribute.editTapAction;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.editorSelectionBehavior = global::SwimmingTool.Resource.Attribute.editorSelectionBehavior;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.enableGroupSeparator = global::SwimmingTool.Resource.Attribute.enableGroupSeparator;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.fontSize = global::SwimmingTool.Resource.Attribute.fontSize;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.frozenColumnsCount = global::SwimmingTool.Resource.Attribute.frozenColumnsCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.frozenRowsCount = global::SwimmingTool.Resource.Attribute.frozenRowsCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.gridRowHeight = global::SwimmingTool.Resource.Attribute.gridRowHeight;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.gridSelectionMode = global::SwimmingTool.Resource.Attribute.gridSelectionMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.groupingMode = global::SwimmingTool.Resource.Attribute.groupingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.headerRowHeight = global::SwimmingTool.Resource.Attribute.headerRowHeight;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.indentColumnWidth = global::SwimmingTool.Resource.Attribute.indentColumnWidth;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.isBusy = global::SwimmingTool.Resource.Attribute.isBusy;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.loadMorePosition = global::SwimmingTool.Resource.Attribute.loadMorePosition;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.loadMoreText = global::SwimmingTool.Resource.Attribute.loadMoreText;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.maxSwipeOffset = global::SwimmingTool.Resource.Attribute.maxSwipeOffset;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.maximumDecimalDigits = global::SwimmingTool.Resource.Attribute.maximumDecimalDigits;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.numberFormat = global::SwimmingTool.Resource.Attribute.numberFormat;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.numericButtonBackground = global::SwimmingTool.Resource.Attribute.numericButtonBackground;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.numericButtonCount = global::SwimmingTool.Resource.Attribute.numericButtonCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.numericTextBoxValue = global::SwimmingTool.Resource.Attribute.numericTextBoxValue;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.orientation = global::SwimmingTool.Resource.Attribute.orientation;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.pageCount = global::SwimmingTool.Resource.Attribute.pageCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.pageSize = global::SwimmingTool.Resource.Attribute.pageSize;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.parsingMode = global::SwimmingTool.Resource.Attribute.parsingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.percentDisplayMode = global::SwimmingTool.Resource.Attribute.percentDisplayMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.resizingMode = global::SwimmingTool.Resource.Attribute.resizingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.rowHeaderWidth = global::SwimmingTool.Resource.Attribute.rowHeaderWidth;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.scrollingMode = global::SwimmingTool.Resource.Attribute.scrollingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.selectAllOnFocus = global::SwimmingTool.Resource.Attribute.selectAllOnFocus;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.selectedIndex = global::SwimmingTool.Resource.Attribute.selectedIndex;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.selectionForeground = global::SwimmingTool.Resource.Attribute.selectionForeground;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.showRowHeader = global::SwimmingTool.Resource.Attribute.showRowHeader;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.sortTapAction = global::SwimmingTool.Resource.Attribute.sortTapAction;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.useOnDemandPaging = global::SwimmingTool.Resource.Attribute.useOnDemandPaging;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.valueChangeMode = global::SwimmingTool.Resource.Attribute.valueChangeMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.verticalOverScrollMode = global::SwimmingTool.Resource.Attribute.verticalOverScrollMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.watermark = global::SwimmingTool.Resource.Attribute.watermark;
			global::Syncfusion.SfGridConverter.Android.Resource.Attribute.watermarkColor = global::SwimmingTool.Resource.Attribute.watermarkColor;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.Ascending = global::SwimmingTool.Resource.Drawable.Ascending;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.Descending = global::SwimmingTool.Resource.Drawable.Descending;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.Drag_and_Drop_Icon = global::SwimmingTool.Resource.Drawable.Drag_and_Drop_Icon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.DragDown = global::SwimmingTool.Resource.Drawable.DragDown;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.DragUp = global::SwimmingTool.Resource.Drawable.DragUp;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.error2 = global::SwimmingTool.Resource.Drawable.error2;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.FirstPageIcon = global::SwimmingTool.Resource.Drawable.FirstPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.GroupCollapse = global::SwimmingTool.Resource.Drawable.GroupCollapse;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.GroupExpander = global::SwimmingTool.Resource.Drawable.GroupExpander;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.GroupIcon_Android = global::SwimmingTool.Resource.Drawable.GroupIcon_Android;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.LastPageIcon = global::SwimmingTool.Resource.Drawable.LastPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.NextPageIcon = global::SwimmingTool.Resource.Drawable.NextPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.PrevPageIcon = global::SwimmingTool.Resource.Drawable.PrevPageIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.ResizingIcon = global::SwimmingTool.Resource.Drawable.ResizingIcon;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.Sort = global::SwimmingTool.Resource.Drawable.Sort;
			global::Syncfusion.SfGridConverter.Android.Resource.Drawable.SortDescending = global::SwimmingTool.Resource.Drawable.SortDescending;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.auto = global::SwimmingTool.Resource.Id.auto;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.bottom = global::SwimmingTool.Resource.Id.bottom;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.bounce = global::SwimmingTool.Resource.Id.bounce;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.compute = global::SwimmingTool.Resource.Id.compute;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.decimalMode = global::SwimmingTool.Resource.Id.decimalMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.doubleMode = global::SwimmingTool.Resource.Id.doubleMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.doubleTap = global::SwimmingTool.Resource.Id.doubleTap;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.horizontal = global::SwimmingTool.Resource.Id.horizontal;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.lastCoulmnFill = global::SwimmingTool.Resource.Id.lastCoulmnFill;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.line = global::SwimmingTool.Resource.Id.line;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.moveLast = global::SwimmingTool.Resource.Id.moveLast;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.multiple = global::SwimmingTool.Resource.Id.multiple;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.none = global::SwimmingTool.Resource.Id.none;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.onKeyFocus = global::SwimmingTool.Resource.Id.onKeyFocus;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.onLostFocus = global::SwimmingTool.Resource.Id.onLostFocus;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.onMoved = global::SwimmingTool.Resource.Id.onMoved;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.onTap = global::SwimmingTool.Resource.Id.onTap;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.onTouchUp = global::SwimmingTool.Resource.Id.onTouchUp;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.pixel = global::SwimmingTool.Resource.Id.pixel;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.pixelLine = global::SwimmingTool.Resource.Id.pixelLine;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.selectAll = global::SwimmingTool.Resource.Id.selectAll;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.single = global::SwimmingTool.Resource.Id.single;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.singleDeSelect = global::SwimmingTool.Resource.Id.singleDeSelect;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.singleTap = global::SwimmingTool.Resource.Id.singleTap;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.star = global::SwimmingTool.Resource.Id.star;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.top = global::SwimmingTool.Resource.Id.top;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.value = global::SwimmingTool.Resource.Id.value;
			global::Syncfusion.SfGridConverter.Android.Resource.Id.vertical = global::SwimmingTool.Resource.Id.vertical;
			global::Syncfusion.SfGridConverter.Android.Resource.Layout.ScrollViewer = global::SwimmingTool.Resource.Layout.ScrollViewer;
			global::Syncfusion.SfGridConverter.Android.Resource.String.library_name = global::SwimmingTool.Resource.String.library_name;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid = global::SwimmingTool.Resource.Styleable.SfDataGrid;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowDraggingColumn = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowDraggingColumn;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowDraggingRow = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowDraggingRow;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowEditing = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowEditing;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowGroupExpandCollapse = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowGroupExpandCollapse;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowLoadMore = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowLoadMore;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowMultiSorting = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowMultiSorting;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowPullToRefresh = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowPullToRefresh;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowResizingColumn = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowResizingColumn;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowSorting = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowSorting;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowSwiping = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowSwiping;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_allowTriStateSorting = global::SwimmingTool.Resource.Styleable.SfDataGrid_allowTriStateSorting;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_alternationCount = global::SwimmingTool.Resource.Styleable.SfDataGrid_alternationCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_autoExpandGroups = global::SwimmingTool.Resource.Styleable.SfDataGrid_autoExpandGroups;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_autoGenerateColumns = global::SwimmingTool.Resource.Styleable.SfDataGrid_autoGenerateColumns;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_columnSizer = global::SwimmingTool.Resource.Styleable.SfDataGrid_columnSizer;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_editTapAction = global::SwimmingTool.Resource.Styleable.SfDataGrid_editTapAction;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_editorSelectionBehavior = global::SwimmingTool.Resource.Styleable.SfDataGrid_editorSelectionBehavior;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_frozenColumnsCount = global::SwimmingTool.Resource.Styleable.SfDataGrid_frozenColumnsCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_frozenRowsCount = global::SwimmingTool.Resource.Styleable.SfDataGrid_frozenRowsCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_gridRowHeight = global::SwimmingTool.Resource.Styleable.SfDataGrid_gridRowHeight;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_gridSelectionMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_gridSelectionMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_groupingMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_groupingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_headerRowHeight = global::SwimmingTool.Resource.Styleable.SfDataGrid_headerRowHeight;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_indentColumnWidth = global::SwimmingTool.Resource.Styleable.SfDataGrid_indentColumnWidth;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_isBusy = global::SwimmingTool.Resource.Styleable.SfDataGrid_isBusy;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_loadMorePosition = global::SwimmingTool.Resource.Styleable.SfDataGrid_loadMorePosition;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_loadMoreText = global::SwimmingTool.Resource.Styleable.SfDataGrid_loadMoreText;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_maxSwipeOffset = global::SwimmingTool.Resource.Styleable.SfDataGrid_maxSwipeOffset;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_resizingMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_resizingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_rowHeaderWidth = global::SwimmingTool.Resource.Styleable.SfDataGrid_rowHeaderWidth;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_scrollingMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_scrollingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_selectedIndex = global::SwimmingTool.Resource.Styleable.SfDataGrid_selectedIndex;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_showRowHeader = global::SwimmingTool.Resource.Styleable.SfDataGrid_showRowHeader;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_sortTapAction = global::SwimmingTool.Resource.Styleable.SfDataGrid_sortTapAction;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataGrid_verticalOverScrollMode = global::SwimmingTool.Resource.Styleable.SfDataGrid_verticalOverScrollMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager = global::SwimmingTool.Resource.Styleable.SfDataPager;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager_numericButtonBackground = global::SwimmingTool.Resource.Styleable.SfDataPager_numericButtonBackground;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager_numericButtonCount = global::SwimmingTool.Resource.Styleable.SfDataPager_numericButtonCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager_orientation = global::SwimmingTool.Resource.Styleable.SfDataPager_orientation;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager_pageCount = global::SwimmingTool.Resource.Styleable.SfDataPager_pageCount;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager_pageSize = global::SwimmingTool.Resource.Styleable.SfDataPager_pageSize;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager_selectionForeground = global::SwimmingTool.Resource.Styleable.SfDataPager_selectionForeground;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfDataPager_useOnDemandPaging = global::SwimmingTool.Resource.Styleable.SfDataPager_useOnDemandPaging;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox = global::SwimmingTool.Resource.Styleable.SfNumericTextBox;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_allowNull = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_allowNull;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_borderColor = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_borderColor;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_culture = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_culture;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_enableGroupSeparator = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_enableGroupSeparator;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_fontSize = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_fontSize;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_numberFormat = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_numberFormat;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_numericTextBoxValue = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_numericTextBoxValue;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_parsingMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_parsingMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_percentDisplayMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_percentDisplayMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_selectAllOnFocus = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_selectAllOnFocus;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_valueChangeMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_valueChangeMode;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_watermark = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_watermark;
			global::Syncfusion.SfGridConverter.Android.Resource.Styleable.SfNumericTextBox_watermarkColor = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_watermarkColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.allowNull = global::SwimmingTool.Resource.Attribute.allowNull;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.borderColor = global::SwimmingTool.Resource.Attribute.borderColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.culture = global::SwimmingTool.Resource.Attribute.culture;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.enableGroupSeparator = global::SwimmingTool.Resource.Attribute.enableGroupSeparator;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.fontSize = global::SwimmingTool.Resource.Attribute.fontSize;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.maximumDecimalDigits = global::SwimmingTool.Resource.Attribute.maximumDecimalDigits;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.numberFormat = global::SwimmingTool.Resource.Attribute.numberFormat;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.numericTextBoxValue = global::SwimmingTool.Resource.Attribute.numericTextBoxValue;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.parsingMode = global::SwimmingTool.Resource.Attribute.parsingMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.percentDisplayMode = global::SwimmingTool.Resource.Attribute.percentDisplayMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.selectAllOnFocus = global::SwimmingTool.Resource.Attribute.selectAllOnFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.valueChangeMode = global::SwimmingTool.Resource.Attribute.valueChangeMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.watermark = global::SwimmingTool.Resource.Attribute.watermark;
			global::Com.Syncfusion.Numerictextbox.Resource.Attribute.watermarkColor = global::SwimmingTool.Resource.Attribute.watermarkColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.compute = global::SwimmingTool.Resource.Id.compute;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.decimalMode = global::SwimmingTool.Resource.Id.decimalMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.doubleMode = global::SwimmingTool.Resource.Id.doubleMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.onKeyFocus = global::SwimmingTool.Resource.Id.onKeyFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.onLostFocus = global::SwimmingTool.Resource.Id.onLostFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Id.value = global::SwimmingTool.Resource.Id.value;
			global::Com.Syncfusion.Numerictextbox.Resource.String.library_name = global::SwimmingTool.Resource.String.library_name;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox = global::SwimmingTool.Resource.Styleable.SfNumericTextBox;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_allowNull = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_allowNull;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_borderColor = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_borderColor;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_culture = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_culture;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_enableGroupSeparator = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_enableGroupSeparator;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_fontSize = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_fontSize;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_maximumDecimalDigits;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_numberFormat = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_numberFormat;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_numericTextBoxValue = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_numericTextBoxValue;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_parsingMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_parsingMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_percentDisplayMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_percentDisplayMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_selectAllOnFocus = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_selectAllOnFocus;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_valueChangeMode = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_valueChangeMode;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_watermark = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_watermark;
			global::Com.Syncfusion.Numerictextbox.Resource.Styleable.SfNumericTextBox_watermarkColor = global::SwimmingTool.Resource.Styleable.SfNumericTextBox_watermarkColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010034
			public const int allowDraggingColumn = 2130772020;
			
			// aapt resource value: 0x7f010036
			public const int allowDraggingRow = 2130772022;
			
			// aapt resource value: 0x7f010027
			public const int allowEditing = 2130772007;
			
			// aapt resource value: 0x7f010026
			public const int allowGroupExpandCollapse = 2130772006;
			
			// aapt resource value: 0x7f01002f
			public const int allowLoadMore = 2130772015;
			
			// aapt resource value: 0x7f010022
			public const int allowMultiSorting = 2130772002;
			
			// aapt resource value: 0x7f010015
			public const int allowNull = 2130771989;
			
			// aapt resource value: 0x7f010032
			public const int allowPullToRefresh = 2130772018;
			
			// aapt resource value: 0x7f01001c
			public const int allowResizingColumn = 2130771996;
			
			// aapt resource value: 0x7f010020
			public const int allowSorting = 2130772000;
			
			// aapt resource value: 0x7f010038
			public const int allowSwiping = 2130772024;
			
			// aapt resource value: 0x7f010021
			public const int allowTriStateSorting = 2130772001;
			
			// aapt resource value: 0x7f010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7f01002e
			public const int alternationCount = 2130772014;
			
			// aapt resource value: 0x7f010025
			public const int autoExpandGroups = 2130772005;
			
			// aapt resource value: 0x7f01001a
			public const int autoGenerateColumns = 2130771994;
			
			// aapt resource value: 0x7f010016
			public const int borderColor = 2130771990;
			
			// aapt resource value: 0x7f01003a
			public const int columnSizer = 2130772026;
			
			// aapt resource value: 0x7f010018
			public const int culture = 2130771992;
			
			// aapt resource value: 0x7f010028
			public const int editTapAction = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int editorSelectionBehavior = 2130772009;
			
			// aapt resource value: 0x7f01000f
			public const int enableGroupSeparator = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int font = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderAuthority = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderCerts = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchStrategy = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderFetchTimeout = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderPackage = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderQuery = 2130771971;
			
			// aapt resource value: 0x7f010014
			public const int fontSize = 2130771988;
			
			// aapt resource value: 0x7f010007
			public const int fontStyle = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int fontVariationSettings = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int fontWeight = 2130771977;
			
			// aapt resource value: 0x7f010035
			public const int frozenColumnsCount = 2130772021;
			
			// aapt resource value: 0x7f010037
			public const int frozenRowsCount = 2130772023;
			
			// aapt resource value: 0x7f01003b
			public const int gridRowHeight = 2130772027;
			
			// aapt resource value: 0x7f01002a
			public const int gridSelectionMode = 2130772010;
			
			// aapt resource value: 0x7f010024
			public const int groupingMode = 2130772004;
			
			// aapt resource value: 0x7f01003c
			public const int headerRowHeight = 2130772028;
			
			// aapt resource value: 0x7f01001b
			public const int indentColumnWidth = 2130771995;
			
			// aapt resource value: 0x7f010033
			public const int isBusy = 2130772019;
			
			// aapt resource value: 0x7f010031
			public const int loadMorePosition = 2130772017;
			
			// aapt resource value: 0x7f010030
			public const int loadMoreText = 2130772016;
			
			// aapt resource value: 0x7f010039
			public const int maxSwipeOffset = 2130772025;
			
			// aapt resource value: 0x7f010012
			public const int maximumDecimalDigits = 2130771986;
			
			// aapt resource value: 0x7f010010
			public const int numberFormat = 2130771984;
			
			// aapt resource value: 0x7f010042
			public const int numericButtonBackground = 2130772034;
			
			// aapt resource value: 0x7f01003d
			public const int numericButtonCount = 2130772029;
			
			// aapt resource value: 0x7f010019
			public const int numericTextBoxValue = 2130771993;
			
			// aapt resource value: 0x7f010040
			public const int orientation = 2130772032;
			
			// aapt resource value: 0x7f01003f
			public const int pageCount = 2130772031;
			
			// aapt resource value: 0x7f01003e
			public const int pageSize = 2130772030;
			
			// aapt resource value: 0x7f01000c
			public const int parsingMode = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int percentDisplayMode = 2130771981;
			
			// aapt resource value: 0x7f01001d
			public const int resizingMode = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int rowHeaderWidth = 2130771998;
			
			// aapt resource value: 0x7f01002c
			public const int scrollingMode = 2130772012;
			
			// aapt resource value: 0x7f010013
			public const int selectAllOnFocus = 2130771987;
			
			// aapt resource value: 0x7f01002b
			public const int selectedIndex = 2130772011;
			
			// aapt resource value: 0x7f010043
			public const int selectionForeground = 2130772035;
			
			// aapt resource value: 0x7f01001f
			public const int showRowHeader = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int sortTapAction = 2130772003;
			
			// aapt resource value: 0x7f01000b
			public const int ttcIndex = 2130771979;
			
			// aapt resource value: 0x7f010041
			public const int useOnDemandPaging = 2130772033;
			
			// aapt resource value: 0x7f01000e
			public const int valueChangeMode = 2130771982;
			
			// aapt resource value: 0x7f01002d
			public const int verticalOverScrollMode = 2130772013;
			
			// aapt resource value: 0x7f010011
			public const int watermark = 2130771985;
			
			// aapt resource value: 0x7f010017
			public const int watermarkColor = 2130771991;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int notification_action_color_filter = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int notification_icon_bg_color = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ripple_material_light = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int secondary_text_default_material_light = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060004
			public const int compat_button_inset_horizontal_material = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int compat_button_inset_vertical_material = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int compat_button_padding_horizontal_material = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int compat_button_padding_vertical_material = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int compat_control_corner_material = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int compat_notification_large_icon_max_height = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int compat_notification_large_icon_max_width = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int notification_action_icon_size = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int notification_action_text_size = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int notification_big_circle_margin = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int notification_content_margin_start = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int notification_large_icon_height = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int notification_large_icon_width = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int notification_main_column_padding_top = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int notification_media_narrow_margin = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int notification_right_icon_size = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int notification_right_side_padding_top = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int notification_small_icon_background_padding = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int notification_small_icon_size_as_large = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_subtext_size = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int notification_top_pad = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int notification_top_pad_large_text = 2131099669;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ascending = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Descending = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Drag_and_Drop_Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int DragDown = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DragUp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int error2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int FirstPageIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GroupCollapse = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GroupExpander = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int GroupIcon_Android = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int LastPageIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int NextPageIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_action_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_bg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int notification_bg_low = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int notification_bg_low_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int notification_bg_low_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int notification_bg_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int notification_bg_normal_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int notification_icon_background = 2130837523;
			
			// aapt resource value: 0x7f02001a
			public const int notification_template_icon_bg = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_template_icon_low_bg = 2130837531;
			
			// aapt resource value: 0x7f020014
			public const int notification_tile_bg = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int notify_panel_notification_icon_bg = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int PrevPageIcon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ResizingIcon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Sort = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SortDescending = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090055
			public const int HomeButton = 2131296341;
			
			// aapt resource value: 0x7f090054
			public const int TextRecomendacion = 2131296340;
			
			// aapt resource value: 0x7f090041
			public const int acceptButton = 2131296321;
			
			// aapt resource value: 0x7f090045
			public const int action_container = 2131296325;
			
			// aapt resource value: 0x7f090051
			public const int action_divider = 2131296337;
			
			// aapt resource value: 0x7f090046
			public const int action_image = 2131296326;
			
			// aapt resource value: 0x7f090047
			public const int action_text = 2131296327;
			
			// aapt resource value: 0x7f090052
			public const int actions = 2131296338;
			
			// aapt resource value: 0x7f090008
			public const int async = 2131296264;
			
			// aapt resource value: 0x7f090024
			public const int auto = 2131296292;
			
			// aapt resource value: 0x7f090009
			public const int blocking = 2131296265;
			
			// aapt resource value: 0x7f090022
			public const int bottom = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int bounce = 2131296289;
			
			// aapt resource value: 0x7f090031
			public const int brazadaButton = 2131296305;
			
			// aapt resource value: 0x7f090062
			public const int brazadaTextView = 2131296354;
			
			// aapt resource value: 0x7f09003e
			public const int brazoEditText = 2131296318;
			
			// aapt resource value: 0x7f090042
			public const int cancelButton = 2131296322;
			
			// aapt resource value: 0x7f090050
			public const int chronometer = 2131296336;
			
			// aapt resource value: 0x7f09000f
			public const int compute = 2131296271;
			
			// aapt resource value: 0x7f090058
			public const int consultarButton = 2131296344;
			
			// aapt resource value: 0x7f09000d
			public const int decimalMode = 2131296269;
			
			// aapt resource value: 0x7f090034
			public const int documentEditText = 2131296308;
			
			// aapt resource value: 0x7f090057
			public const int documentoEditText = 2131296343;
			
			// aapt resource value: 0x7f09005a
			public const int documentoTextView = 2131296346;
			
			// aapt resource value: 0x7f09000e
			public const int doubleMode = 2131296270;
			
			// aapt resource value: 0x7f090015
			public const int doubleTap = 2131296277;
			
			// aapt resource value: 0x7f09005f
			public const int estatTextView = 2131296351;
			
			// aapt resource value: 0x7f09003c
			public const int estaturaEditText = 2131296316;
			
			// aapt resource value: 0x7f090060
			public const int estaturaTextView = 2131296352;
			
			// aapt resource value: 0x7f090033
			public const int finishButton = 2131296307;
			
			// aapt resource value: 0x7f09000a
			public const int forever = 2131296266;
			
			// aapt resource value: 0x7f090039
			public const int hombreRadioButton = 2131296313;
			
			// aapt resource value: 0x7f090059
			public const int homeButton = 2131296345;
			
			// aapt resource value: 0x7f090027
			public const int horizontal = 2131296295;
			
			// aapt resource value: 0x7f090049
			public const int icon = 2131296329;
			
			// aapt resource value: 0x7f090053
			public const int icon_group = 2131296339;
			
			// aapt resource value: 0x7f09004c
			public const int info = 2131296332;
			
			// aapt resource value: 0x7f090043
			public const int ingresarButton = 2131296323;
			
			// aapt resource value: 0x7f09000b
			public const int italic = 2131296267;
			
			// aapt resource value: 0x7f090025
			public const int lastCoulmnFill = 2131296293;
			
			// aapt resource value: 0x7f09001e
			public const int line = 2131296286;
			
			// aapt resource value: 0x7f090000
			public const int line1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int line3 = 2131296257;
			
			// aapt resource value: 0x7f09002a
			public const int linearLayout1 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int linearLayout2 = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int linearLayout3 = 2131296300;
			
			// aapt resource value: 0x7f090036
			public const int linearLayout4 = 2131296310;
			
			// aapt resource value: 0x7f09003d
			public const int linearLayout5 = 2131296317;
			
			// aapt resource value: 0x7f09003f
			public const int linearLayout6 = 2131296319;
			
			// aapt resource value: 0x7f090040
			public const int linearLayout7 = 2131296320;
			
			// aapt resource value: 0x7f09003b
			public const int linearLayout9 = 2131296315;
			
			// aapt resource value: 0x7f090029
			public const int ll_container_surface_view = 2131296297;
			
			// aapt resource value: 0x7f09001a
			public const int moveLast = 2131296282;
			
			// aapt resource value: 0x7f09003a
			public const int mujerRadioButton = 2131296314;
			
			// aapt resource value: 0x7f090017
			public const int multiple = 2131296279;
			
			// aapt resource value: 0x7f090035
			public const int nombreEditText = 2131296309;
			
			// aapt resource value: 0x7f09005c
			public const int nombreTextView = 2131296348;
			
			// aapt resource value: 0x7f09001c
			public const int none = 2131296284;
			
			// aapt resource value: 0x7f09000c
			public const int normal = 2131296268;
			
			// aapt resource value: 0x7f09004e
			public const int notification_background = 2131296334;
			
			// aapt resource value: 0x7f09004a
			public const int notification_main_column = 2131296330;
			
			// aapt resource value: 0x7f090048
			public const int notification_main_column_container = 2131296328;
			
			// aapt resource value: 0x7f090032
			public const int numBrazadaTextView = 2131296306;
			
			// aapt resource value: 0x7f090011
			public const int onKeyFocus = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int onLostFocus = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int onMoved = 2131296275;
			
			// aapt resource value: 0x7f090019
			public const int onTap = 2131296281;
			
			// aapt resource value: 0x7f090014
			public const int onTouchUp = 2131296276;
			
			// aapt resource value: 0x7f09001f
			public const int pixel = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int pixelLine = 2131296288;
			
			// aapt resource value: 0x7f090038
			public const int radioGroup1 = 2131296312;
			
			// aapt resource value: 0x7f09002e
			public const int resetButton = 2131296302;
			
			// aapt resource value: 0x7f090063
			public const int resultDataGrid = 2131296355;
			
			// aapt resource value: 0x7f09004d
			public const int right_icon = 2131296333;
			
			// aapt resource value: 0x7f09004b
			public const int right_side = 2131296331;
			
			// aapt resource value: 0x7f09001b
			public const int selectAll = 2131296283;
			
			// aapt resource value: 0x7f090056
			public const int sessionButton = 2131296342;
			
			// aapt resource value: 0x7f090037
			public const int sexoRadioButton = 2131296311;
			
			// aapt resource value: 0x7f09005e
			public const int sexoTextView = 2131296350;
			
			// aapt resource value: 0x7f090018
			public const int single = 2131296280;
			
			// aapt resource value: 0x7f09001d
			public const int singleDeSelect = 2131296285;
			
			// aapt resource value: 0x7f090016
			public const int singleTap = 2131296278;
			
			// aapt resource value: 0x7f090026
			public const int star = 2131296294;
			
			// aapt resource value: 0x7f09002d
			public const int startStopButton = 2131296301;
			
			// aapt resource value: 0x7f090002
			public const int tag_transition_group = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int tag_unhandled_key_event_manager = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int tag_unhandled_key_listeners = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int text = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int text2 = 2131296262;
			
			// aapt resource value: 0x7f09002f
			public const int textView1 = 2131296303;
			
			// aapt resource value: 0x7f09005b
			public const int textView2 = 2131296347;
			
			// aapt resource value: 0x7f09005d
			public const int textView3 = 2131296349;
			
			// aapt resource value: 0x7f090061
			public const int textView6 = 2131296353;
			
			// aapt resource value: 0x7f09004f
			public const int time = 2131296335;
			
			// aapt resource value: 0x7f090030
			public const int timeTextView = 2131296304;
			
			// aapt resource value: 0x7f090007
			public const int title = 2131296263;
			
			// aapt resource value: 0x7f090023
			public const int top = 2131296291;
			
			// aapt resource value: 0x7f090010
			public const int value = 2131296272;
			
			// aapt resource value: 0x7f090044
			public const int verSesionButton = 2131296324;
			
			// aapt resource value: 0x7f090028
			public const int vertical = 2131296296;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_maxnum = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Brazadas = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_action_tombstone = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_custom_big = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_icon_group = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_part_chronometer = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_part_time = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Resultado = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ScrollViewer = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Tabla = 2130968586;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int library_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Info = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Line2 = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Widget_Compat_NotificationActionContainer = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Widget_Compat_NotificationActionText = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] FontFamily = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			public static int[] SfDataGrid = new int[] {
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028};
			
			// aapt resource value: 26
			public const int SfDataGrid_allowDraggingColumn = 26;
			
			// aapt resource value: 28
			public const int SfDataGrid_allowDraggingRow = 28;
			
			// aapt resource value: 13
			public const int SfDataGrid_allowEditing = 13;
			
			// aapt resource value: 12
			public const int SfDataGrid_allowGroupExpandCollapse = 12;
			
			// aapt resource value: 21
			public const int SfDataGrid_allowLoadMore = 21;
			
			// aapt resource value: 8
			public const int SfDataGrid_allowMultiSorting = 8;
			
			// aapt resource value: 24
			public const int SfDataGrid_allowPullToRefresh = 24;
			
			// aapt resource value: 2
			public const int SfDataGrid_allowResizingColumn = 2;
			
			// aapt resource value: 6
			public const int SfDataGrid_allowSorting = 6;
			
			// aapt resource value: 30
			public const int SfDataGrid_allowSwiping = 30;
			
			// aapt resource value: 7
			public const int SfDataGrid_allowTriStateSorting = 7;
			
			// aapt resource value: 20
			public const int SfDataGrid_alternationCount = 20;
			
			// aapt resource value: 11
			public const int SfDataGrid_autoExpandGroups = 11;
			
			// aapt resource value: 0
			public const int SfDataGrid_autoGenerateColumns = 0;
			
			// aapt resource value: 32
			public const int SfDataGrid_columnSizer = 32;
			
			// aapt resource value: 14
			public const int SfDataGrid_editTapAction = 14;
			
			// aapt resource value: 15
			public const int SfDataGrid_editorSelectionBehavior = 15;
			
			// aapt resource value: 27
			public const int SfDataGrid_frozenColumnsCount = 27;
			
			// aapt resource value: 29
			public const int SfDataGrid_frozenRowsCount = 29;
			
			// aapt resource value: 33
			public const int SfDataGrid_gridRowHeight = 33;
			
			// aapt resource value: 16
			public const int SfDataGrid_gridSelectionMode = 16;
			
			// aapt resource value: 10
			public const int SfDataGrid_groupingMode = 10;
			
			// aapt resource value: 34
			public const int SfDataGrid_headerRowHeight = 34;
			
			// aapt resource value: 1
			public const int SfDataGrid_indentColumnWidth = 1;
			
			// aapt resource value: 25
			public const int SfDataGrid_isBusy = 25;
			
			// aapt resource value: 23
			public const int SfDataGrid_loadMorePosition = 23;
			
			// aapt resource value: 22
			public const int SfDataGrid_loadMoreText = 22;
			
			// aapt resource value: 31
			public const int SfDataGrid_maxSwipeOffset = 31;
			
			// aapt resource value: 3
			public const int SfDataGrid_resizingMode = 3;
			
			// aapt resource value: 4
			public const int SfDataGrid_rowHeaderWidth = 4;
			
			// aapt resource value: 18
			public const int SfDataGrid_scrollingMode = 18;
			
			// aapt resource value: 17
			public const int SfDataGrid_selectedIndex = 17;
			
			// aapt resource value: 5
			public const int SfDataGrid_showRowHeader = 5;
			
			// aapt resource value: 9
			public const int SfDataGrid_sortTapAction = 9;
			
			// aapt resource value: 19
			public const int SfDataGrid_verticalOverScrollMode = 19;
			
			public static int[] SfDataPager = new int[] {
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035};
			
			// aapt resource value: 5
			public const int SfDataPager_numericButtonBackground = 5;
			
			// aapt resource value: 0
			public const int SfDataPager_numericButtonCount = 0;
			
			// aapt resource value: 3
			public const int SfDataPager_orientation = 3;
			
			// aapt resource value: 2
			public const int SfDataPager_pageCount = 2;
			
			// aapt resource value: 1
			public const int SfDataPager_pageSize = 1;
			
			// aapt resource value: 6
			public const int SfDataPager_selectionForeground = 6;
			
			// aapt resource value: 4
			public const int SfDataPager_useOnDemandPaging = 4;
			
			public static int[] SfNumericTextBox = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 9
			public const int SfNumericTextBox_allowNull = 9;
			
			// aapt resource value: 10
			public const int SfNumericTextBox_borderColor = 10;
			
			// aapt resource value: 12
			public const int SfNumericTextBox_culture = 12;
			
			// aapt resource value: 3
			public const int SfNumericTextBox_enableGroupSeparator = 3;
			
			// aapt resource value: 8
			public const int SfNumericTextBox_fontSize = 8;
			
			// aapt resource value: 6
			public const int SfNumericTextBox_maximumDecimalDigits = 6;
			
			// aapt resource value: 4
			public const int SfNumericTextBox_numberFormat = 4;
			
			// aapt resource value: 13
			public const int SfNumericTextBox_numericTextBoxValue = 13;
			
			// aapt resource value: 0
			public const int SfNumericTextBox_parsingMode = 0;
			
			// aapt resource value: 1
			public const int SfNumericTextBox_percentDisplayMode = 1;
			
			// aapt resource value: 7
			public const int SfNumericTextBox_selectAllOnFocus = 7;
			
			// aapt resource value: 2
			public const int SfNumericTextBox_valueChangeMode = 2;
			
			// aapt resource value: 5
			public const int SfNumericTextBox_watermark = 5;
			
			// aapt resource value: 11
			public const int SfNumericTextBox_watermarkColor = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
